import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        padding: 10,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    headerText: {
        fontSize: 18,
        fontWeight: 'bold',
    },
    subHeaderText: {
        fontSize: 14,
        color: '#888',
    },
    helpText: {
        color: '#FF2B85',
        fontWeight: 'bold',
        fontSize: 14,
    },
    mapContainer: {
        height: '50%',
        marginBottom: 20,
    },
    map: {
        width: '100%',
        height: '100%',
    },
    centerButton: {
        position: 'absolute',
        bottom: 80,
        left: '50%',
        marginLeft: -60,
        backgroundColor: '#FF2B85',
        padding: 10,
        borderRadius: 50,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    centerButtonText: {
        color: '#fff',
        fontSize: 12,
        marginLeft: 5,
    },
    cancelOrderButton: {
        position: 'absolute',
        bottom: 20,
        left: '50%',
        marginLeft: -60,
        backgroundColor: '#FF2B85',
        padding: 12,
        borderRadius: 50,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelOrderText: {
        color: '#FF2B85',
        fontWeight: 'bold',
        fontSize: 14
    },
    errorContainer: {
        position: 'absolute',
        bottom: 10,
        left: '50%',
        marginLeft: -150,
        backgroundColor: '#FFDDDD',
        padding: 10,
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
    },
    errorText: {
        color: '#FF0000',
        fontWeight: 'bold',
    },
    tipContainer: {
        flex: 1,
        justifyContent: 'flex-end',
        paddingBottom: 20,
    },
    tipContent: {
        backgroundColor: '#F9F9F9',
        padding: 15,
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
    },
    tipTextCenter: {
        textAlign: 'center',
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#333',
    },
    tipRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 15,
    },
    tipDetails: {
        marginLeft: 10,
        flex: 1,
    },
    tipTitle: {
        fontSize: 14,
        fontWeight: 'bold',
    },
    tipDescription: {
        fontSize: 12,
        color: '#FF2B85',
        marginVertical: 5,
    },
    tipOptions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    tipButton: {
        padding: 10,
        borderRadius: 5,
        backgroundColor: 'white',
        marginVertical: 5,
        alignItems: 'center',
        flexDirection: 'row',
        borderWidth: 1,
        borderColor: '#FF2B85',
    },
    selectedTipButton: {
        backgroundColor: '#FF2B85',
    },
    tipAmount: {
        fontSize: 14,
    },
    selectedTipText: {
        color: '#fff',
    },
    tipPayment: {
        fontSize: 14,
        color: '#333',
        marginTop: 10,
    },
    cancelTip: {
        marginTop: 5,
        alignItems: 'center',
    },
    cancelText: {
        fontSize: 14,
        color: '#FF2B85',
    },
    orderReceivedButton: {
        backgroundColor: '#FF2B85',
        borderRadius: 25,
        paddingVertical: 12,
        paddingHorizontal: 30,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    orderReceivedText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    coordinatesContainer: {
        position: 'absolute',
        bottom: 10,
        left: 10,
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        padding: 10,
        borderRadius: 5,
    },
    coordinatesText: {
        fontSize: 12,
        color: '#333',
    },
});
